export default {
  countSystemData: [
    {
      count_num: 510,
      chain: 0,
      day_sync_num: 264,
      day_fill_num: 266,
      day_audit_num: 64,
      system_id: 1,
      system_name: "排污许可证系统",
      day_sync_success_num: 22,
      day_in_num: 246,
      grew: 100,
      count_map_list: [
        { countName: "累计填报量", count_map_num: 246 },
        { countName: "办件同步量", count_map_num: 123 },
        { countName: "办件同步成功量", count_map_num: 11 },
        { countName: "证照同步量", count_map_num: 123 },
        { countName: "证照同步成功量", count_map_num: 11 },
      ],
    },
    {
      count_num: 510,
      chain: 0,
      day_sync_num: 264,
      day_fill_num: 266,
      day_audit_num: 64,
      system_id: 2,
      system_name: "辐射安全许可证系统",
      day_sync_success_num: 22,
      day_in_num: 246,
      grew: 100,
      count_map_list: [
        { countName: "累计填报量", count_map_num: 246 },
        { countName: "办件同步量", count_map_num: 123 },
        { countName: "办件同步成功量", count_map_num: 11 },
        { countName: "证照同步量", count_map_num: 123 },
        { countName: "证照同步成功量", count_map_num: 11 },
      ],
    },
    {
      count_num: 297,
      chain: 0,
      day_sync_num: 132,
      day_fill_num: 133,
      day_audit_num: 32,
      system_id: 3,
      system_name: "环境建设登记表备案系统",
      day_sync_success_num: 11,
      day_in_num: 123,
      grew: 100,
      count_map_list: [
        { countName: "累计填报量", count_map_num: 133 },
        { countName: "累计审批量", count_map_num: 32 },
        { countName: "累计同步量", count_map_num: 132 },
      ],
    },
  ],
  countData: {
    count_num: 1230,
    count_data_list: [
      {
        count_sync_success_num: 22,
        system_id: 1,
        count_sync_num: 264,
        system_name: "排污许可证系统",
        count_in_num: 246,
      },
      {
        count_sync_success_num: 22,
        system_id: 2,
        count_sync_num: 264,
        system_name: "辐射安全许可证系统",
        count_in_num: 246,
      },
      {
        count_sync_success_num: 11,
        system_id: 3,
        count_sync_num: 132,
        system_name: "环境建设登记表备案系统",
        count_in_num: 123,
      },
      {
        count_sync_success_num: 0,
        system_id: 4,
        count_sync_num: 0,
        system_name: "应急预案备案系统",
        count_in_num: 0,
      },
      {
        count_sync_success_num: 0,
        system_id: 5,
        count_sync_num: 0,
        system_name: "环评备案系统",
        count_in_num: 0,
      },
    ],
    count_sync_num: 615,
    count_in_num: 615,
    count_num_bfb: 0,
  },
  dayData: {
    day_sync_num: 660,
    error_log: [
      {
        day_error_sum: 1,
        error_info:
          "SC2112050054915134330582363820;推送企业数据成功;推送水污染情况失败;推送应急人员信息成功;推送文件信息成功;",
        main_type: "0",
        day_err_type_list: [
          {
            day_error_sum: 1,
            error_info:
              "SC2112050054915134330582363820;推送企业数据成功;推送水污染情况失败;推送应急人员信息成功;推送文件信息成功;",
            main_type: "0",
          },
        ],
      },
      {
        day_error_sum: 1,
        error_info: "失败原因：连接超时",
        error_type: "1",
        main_type: "1",
        day_err_type_list: [
          {
            day_error_sum: 1,
            error_info: "失败原因：连接超时",
            error_type: "1",
            main_type: "1",
          },
        ],
      },
      {
        day_error_sum: 1,
        error_info: "失败原因：数据填报一场",
        error_type: "1",
        main_type: "2",
        day_err_type_list: [
          {
            day_error_sum: 1,
            error_info: "失败原因：数据填报一场",
            error_type: "1",
            main_type: "2",
          },
        ],
      },
    ],
    day_in_num: 615,
    day_system_List: [
      {
        day_sync_num: 264,
        day_fill_num: 266,
        day_audit_num: 64,
        system_id: 1,
        system_name: "排污许可证系统",
        day_sync_success_num: 22,
        day_in_num: 246,
      },
      {
        day_sync_num: 264,
        day_fill_num: 266,
        day_audit_num: 64,
        system_id: 2,
        system_name: "辐射安全许可证系统",
        day_sync_success_num: 22,
        day_in_num: 246,
      },
      {
        day_sync_num: 132,
        day_fill_num: 133,
        day_audit_num: 32,
        system_id: 3,
        system_name: "环境建设登记表备案系统",
        day_sync_success_num: 11,
        day_in_num: 123,
      },
    ],
  },
  system_special: { special_num: 123, getway_num: 345, pv_num: 234, id: 1 },
  system_pv: [
    {
      system_id: 2,
      system_name: "辐射安全许可证系统",
      id: 2,
      system_pv: 456,
      system_pic: "333",
    },
    {
      system_id: 1,
      system_name: "排污许可证系统",
      id: 1,
      system_pv: 123,
      system_pic: "ccc",
    },
  ],
};
